name: studio_flow
description: "Sistema de Agendamentos de Ensaios Musicais"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.5.6
  
  # State Management
  provider: ^6.1.2
  
  # Routing
  go_router: ^14.2.0
  
  # HTTP & JSON
  http: ^1.2.1
  
  # Utils
  intl: ^0.19.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.3
  
  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Forms
  mask_text_input_formatter: ^2.9.0
  email_validator: ^2.1.17
  cpf_cnpj_validator: ^2.0.0
  brasil_fields: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
